name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

env:
  # IMPORTANT: Change this to your Docker Hub username/repo
  DOCKER_IMAGE_NAME: puffy3/flask-k8s-app

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
      - name: Verify deployment
        run: kubectl rollout status deployment/flask-app-deployment